### ISSUE TITLE
inputstream-adaptive - is it optional for live games?

### ISSUE THREAD

**Issue by OnceUponALoop** [pigskin/kodi-gamepass#415]
General question - not an issue

Can anyone watch live games without inputstream-adaptive? 
I haven't been able to since last years NFL changes, just wondering if live games without inputstream-adaptive is a valid use-case anymore.

**Comment by OnceUponALoop** [comment]
@aqw - what do you think about this? 
If it's required then we detect it and prompt users with an error if they attempt to play live games, should help us avoid a bunch of unnecessary bug reports.
I can't play live videos without it since the issue came up (#363), but i can play old videos just fine by selecting the stream - I assume it's the same all around and not limited to my config.

**Comment by aqw** [comment]
@OnceUponALoop I'm trying to think of why InputStream would be a requirement for the live streams. It should just be a matter of inspecting the manifest, extracting a particular stream, and passing that to Kodi. Live streams are encrypted, but that information is carried in the stream URI rather than in the manifest. Perhaps that's no longer accurate, but that's my recollection.[1]

I guess my position is: if indeed InputStream-Adaptive is a requirement for watching live games, then yeah, it would be best if we informed users. We could even go so far as to warn them, and then ask them if they are ok with us changing the setting for them (the code is already present for that, I believe).

The "proper" solution here is to figure out what is so different about these live manifests, but I don't have the time for such spelunking right now, and sending someone else down that dark rabbit hole seems cruel. ;-)

That's a long way of saying: yeah, I think this is a good idea. :-)

---Alex

[1] As a side note here, this is another one of the many things that my (now stalled) work in pigskin is attempting to address. We will have recordings of server responses from GamePass, and thus can /finally/ easily diff what the heck has changed. It's a glorious feeling, and should help situations like this immensely.

**Comment by aqw** [comment]
@OnceUponALoop Do you mind if I contact you off list? I looked for an email on your profile, but couldn't find one. If you want, you can just ping me at alex@waite.eu.

Thanks. :-)

---Alex

**Comment by zero3nna** [comment]
I couldn't get xbmc-gamepass live games or replays to work at all without setting `inputstream-adaptive` -> `On`
I'm on Kodi 17.6 on Ubuntu 18.04.1 btw.

**Comment by jm-duke** [comment]
Doing some clean-up and this issue report is really old, so I'm closing it.
